services:
  nginx:
    build: ./nginx
    image: colorblind/nginx
    container_name: nginx
    depends_on: 
      - server
      - client
    ports: 
      - 8080:8080
  database:
    image: postgres
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build: ./Colorblind
    image: colorblind/server
    container_name: server
    expose:
      - 80
    depends_on: 
      - database
    environment:
      - SCHEMA_NAME=colorblind
      - "DB_STRING=host=database;database=postgres;password=postgres;username=postgres"
  client:
    build: ./client
    image: colorblind/client
    container_name: client
    depends_on:
      - server
