name: Integration
on:
  push:
    paths:
      - 'Colorblind/**'
      - 'client/**'

jobs:
  ci:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10.x"
      - name: Run image
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.1.15"
      - name: Install pytest
        run: poetry add pytest
      - name: Run integration tests
        run: poetry run pytest
