# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: actions/compose-action@v1.4.1
      with:
        compose-file: docker-compose.yml
    
    - name: Build image
      working-directory: ./integrationtesting
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "1.1.15"
    - name: Test
      working-directory: ./integrationtesting
      run: poetry run pytest
